### ISSUE TITLE
issue with trust wallet connection

### ISSUE THREAD

**Issue by bansalgaurav852** [nextchapterstudio/walletconnect_qrcode_modal_dart#26] opened 2023-03-25 11:37 UTC
when i connect with trust wallet it show *An unknown error occurred*

**Comment by 3ph** [comment] 2023-03-26 19:56
Hi, is this a duplicate of https://github.com/nextchapterstudio/walletconnect_qrcode_modal_dart/issues/23?

**Closed as not planned** 2023-03-27 22:26 UTC
