### ISSUE TITLE
The modal does not close when the user return to the app

### ISSUE THREAD

**Issue by Martelinok** [nextchapterstudio/walletconnect_qrcode_modal_dart#22] opened 2023-02-01 20:22 UTC
@3ph Hi, we found a problem with the library, when the user wants to connect a wallet and then the user for any reason cancels and then wants to add again, the modal does not hide.  

- A version of the library is 0.1.2 
When the user click in a button call the function `_openWalletConnectModal` and then we call `walletConnectorSdk.connect(context)` this opens the modal.
![Screenshot 2023-02-01 at 3 01 02 PM](https://user-images.githubusercontent.com/9620251/216150692-8a93d576-32a1-4329-9680-585d8ea57a0f.png)
Then we navigate automatically to metamask and tap on cancel.
![Screenshot 2023-02-01 at 3 17 04 PM](https://user-images.githubusercontent.com/9620251/216153848-7fc9ff9f-ea5e-4195-be3d-60c0186e0e33.png)
we try to add it again and when we return to the page the modal stays shown and do not respond.
![Screenshot 2023-02-01 at 3 23 25 PM](https://user-images.githubusercontent.com/9620251/216155147-85629207-f08d-4a43-8a6b-83d0e137da83.png)
you try to add other and it doesn't add.

**Comment by 3ph** [comment] 2023-02-02 02:57
Hi @Martelinok, I've investigated and can confirm that this is indeed an issue. The problem is with the `walletconnect_dart` library - only the first `createSession` call works, for the subsequent ones there is no response to any requests so it never returns. I've tried quite a few things to get around it slightly more nicely but failed. The library doesn't seem to be maintained for the last couple of months and there are a few issues raised with `killSession` not working correctly. However, even with the proposed fixes it still doesn't fix our problem. For now, I'd suggest recreating the whole connector when `connect` doesn't return any session (indicating some error or cancellation).

In the example app this would be around line 165:
```dart
            final session =
                await connector.connect(context).catchError((error) {
              ScaffoldMessenger.of(context)
                  .showSnackBar(SnackBar(content: Text(error)));
              return null;
            });

            if (session != null) {
              setState(() => _state = ConnectionState.connected);
              Future.delayed(Duration.zero, () => _openWalletPage());
            } else {
              connector = EthereumTestConnector(); // <<< THIS WAS ADDED
              setState(() => _state = ConnectionState.connectionCancelled);
            }
```

It's not a very nice workaround but it seems to work. I'll raise a ticket with `walletconnect_dart` and if there is any fix I'll integrate here as well.

**Comment by 3ph** [comment] 2023-02-21 03:02
Closing for now as it's an issue with the underlying library.

**Closed as completed by 3ph** 2023-02-21 03:02 UTC

**Comment by prossion** [comment] 2023-04-26 14:41
Hi! Any updates?

**Comment by 3ph** [comment] 2023-04-26 21:07
Unfortunately no updates. I'd suggest using the workaround above for now, or switch to V2 - V1 sunset is coming soon anyway.
